-- Initial script to create the database and the tables
BEGIN;

-- Drop the table 'rooms' if it exists
DROP TABLE IF EXISTS "rooms" CASCADE;

-- Create the table 'rooms'
CREATE TABLE "rooms" (
    "room_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Drop the table 'users' if it exists
DROP TABLE IF EXISTS "users" CASCADE;

-- Create the table 'users'
CREATE TABLE "users" (
    "user_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "password" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Drop the table 'user_rooms' if it exists (many-to-many relationship between users and rooms)
DROP TABLE IF EXISTS "user_rooms" CASCADE;

-- Create the association table 'user_rooms' (to associate users and rooms)
CREATE TABLE "user_rooms" (
    "user_id" integer NOT NULL,
    "room_id" integer NOT NULL,
    "added_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("user_id", "room_id"),
    FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE,
    FOREIGN KEY ("room_id") REFERENCES "rooms" ("room_id") ON DELETE CASCADE
);

-- Drop the table 'messages' if it exists
DROP TABLE IF EXISTS "messages" CASCADE;

-- Create the table 'messages'
CREATE TABLE "messages" (
    "message_id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "room_id" integer NOT NULL,
    "user_id" integer NOT NULL,
    "message" TEXT NOT NULL,
    "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY ("room_id") REFERENCES "rooms" ("room_id") ON DELETE CASCADE,
    FOREIGN KEY ("user_id") REFERENCES "users" ("user_id") ON DELETE CASCADE
);

-- Commit the transaction
COMMIT;